spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=healthyfood;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always